name: Deploy Documentation (Manual - No Sync)

on:
  # Only allow manual workflow dispatch
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Deployment message/reason'
        required: false
        default: 'Manual deployment without syncing external repos'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install documentation dependencies
        run: |
          pip install -r requirements.txt
          # Note: NOT installing pyyaml since we're not running sync

      - name: Display deployment message
        run: |
          echo "🚀 Manual deployment triggered"
          echo "📝 Message: ${{ github.event.inputs.deploy_message }}"
          echo "⚠️  This deployment uses pre-synced files and does NOT fetch latest from external repos"

      # Build the documentation without running sync
      - name: Build documentation (no sync)
        run: |
          echo "Building documentation without syncing external repos..."
          mkdocs build --verbose --strict
        env:
          # Disable the sync hook by setting an environment variable
          # The sync script should check for this
          DISABLE_README_SYNC: "true"

      # Upload the built site as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4